# Generated by Django 4.2.1 on 2023-05-31 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corbeillepatient',
            name='dateSuppression_debut',
            field=models.DateField(default=datetime.datetime(2023, 5, 31, 15, 42, 23)),
        ),
        migrations.AlterField(
            model_name='corbeillepatient',
            name='dateSuppression_fin',
            field=models.DateField(default=datetime.datetime(2023, 6, 30, 17, 42, 23)),
        ),
    ]
