# Generated by Django 4.2.1 on 2023-05-31 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_alter_corbeillepatient_datesuppression_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corbeillepatient',
            name='dateSuppression_debut',
            field=models.DateField(default=datetime.datetime(2023, 5, 31, 16, 4, 38)),
        ),
        migrations.AlterField(
            model_name='corbeillepatient',
            name='dateSuppression_fin',
            field=models.DateField(default=datetime.datetime(2023, 6, 30, 18, 4, 38)),
        ),
    ]
