# Generated by Django 4.2.1 on 2023-06-01 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_alter_corbeillepatient_datesuppression_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corbeillepatient',
            name='dateSuppression_debut',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 18, 29, 48)),
        ),
        migrations.AlterField(
            model_name='corbeillepatient',
            name='dateSuppression_fin',
            field=models.DateField(default=datetime.datetime(2023, 7, 1, 20, 29, 48)),
        ),
    ]
