# Generated by Django 4.2.1 on 2023-06-05 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_alter_corbeillepatient_datesuppression_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corbeillepatient',
            name='dateSuppression_debut',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 16, 47, 55)),
        ),
        migrations.AlterField(
            model_name='corbeillepatient',
            name='dateSuppression_fin',
            field=models.DateField(default=datetime.datetime(2023, 7, 5, 17, 47, 55)),
        ),
    ]
