# Generated by Django 4.1.5 on 2023-06-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateur', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='dateStart',
            field=models.CharField(default='2023-06-03 00:12:41', max_length=100),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='dateUpdated',
            field=models.CharField(default='2023-06-03 00:12:41', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='dateEnvoie',
            field=models.CharField(default='2023-06-03 00:12:41', max_length=100),
        ),
    ]
