# Generated by Django 4.2.1 on 2023-06-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateur', '0004_alter_conversation_datestart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='dateStart',
            field=models.CharField(default='2023-06-01 20:29:48', max_length=100),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='dateUpdated',
            field=models.CharField(default='2023-06-01 20:29:48', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='dateEnvoie',
            field=models.CharField(default='2023-06-01 20:29:48', max_length=100),
        ),
    ]
